name: Pull Request Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/JotSpot/JotSpot.sln

    - name: Build Solution
      run: dotnet build src/JotSpot/JotSpot.sln --no-restore

    - name: Run Tests
      run: dotnet test src/JotSpot/JotSpot.sln --no-build --verbosity normal
